### ISSUE TITLE
Nudge_Lastet.sh fails to get version numbers.

### ISSUE THREAD

**Issue by dash4385** [rs1278/macOSinstallers#3]
Nudge_Lastet.sh fails to get version numbers.

Line 6 the versionNumber variable fails to get the version number correctly and causes the install to fail.

**Comment by rs1278** [comment]
Can you try running these commands in terminal and reply with what you get?

```
nudgeLatestURL="https://github.com/macadmins/nudge/releases/latest/"
versionUrl=$(curl "${nudgeLatestURL}" -s -L -I -o /dev/null -w '%{url_effective}')
versionNumber="${$(printf "%s" "${versionUrl[@]}" | sed 's@.*/@@' | sed 's/%20/-/g'):1}"
echo $versionUrl "; " $versionNumber
```

Running this on my system gives:
`https://github.com/macadmins/nudge/releases/tag/v1.1.5.81289 ;  1.1.5.81289`

Which is the latest release that came out a few hours prior to writing. The issue could be on your end, or maybe with a different line of code. If the latter, try running the script line by line in the terminal to see where the issue pops up, and let me know what you find.

Thanks for noticing this issue!

**Comment by dash4385** [comment]
Running the Command provided did give me the same results. However when I run it from the script getting this error

Nudge_Latest.sh: line 6: ${$(printf "%s" "${versionUrl[@]}" | sed 's@.*/@@' | sed 's/%20/-/g'):1}: bad substitution

I echoed back some of the variables to see what is being set and this is the result 

versionUrl - https://github.com/macadmins/nudge/releases/tag/v1.1.5.81289
versionNumber -
downloadUrl - https://github.com/macadmins/nudge/releases/download/v/Nudge-.pkg

It is getting the correct versionUrl but fails to set the versionNumber to anything and that is causing the downloadUrl to be wrong.

**Comment by rs1278** [comment]
Nice. Thanks for finding this.

Was able to reproduce on my end and confirm this happens when running the .sh script. Fix is to substitute line 6 for the following two lines

```
versionNumber=$(printf "%s" "${versionUrl[@]}" | sed 's@.*/@@' | sed 's/%20/-/g')
versionNumber=${versionNumber:1}
```

Seems like a bash vs zsh difference. zsh seems to be okay with double substitutions. Will publish a fixed version with the next push.
